# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/


#custom

symbols_count_time:
#文章内是否显示
  symbols: false
  time: false
 # 网页底部是否显示
  total_symbols: true
  total_time: false


# Site
title: Aemaeth0's Notes
subtitle: Stay Simple & Stay Naive
description: EE,IC,Linux,C/C++,Control theory
keywords: 
author: Aemaeth0
language: zh-CN
timezone: Asia/Shanghai

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: https://aemaeth0.xyz
root: /
permalink: archives/:abbrlink.html #year/:month/:day/:title/
abbrlink:
  alg: crc32  # 算法：crc16(default) and crc32
  rep: hex    # 进制：dec(default) and hex
permalink_defaults:

nofollow:
  enable: true
  field: site
  exclude:
    - 'https://github.com/MonostableLSD'
    - 'https://space.bilibili.com/7564745'
    - 'mailto:monostablelss@gmail.com'
    # GitHub: https://github.com/MonostableLSD || fab fa-github
    # E-Mail: mailto:monostablelss@gmail.com || fa fa-envelope
    # WeChat: /images/weChat.png || fab fa-weixin
    # Bilibili: https://space.bilibili.com/7564745 || fa fa-mars

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link.enable: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace:
  
# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ''
  per_page: 10
  order_by: -date
  
# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: next

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  - type: git   # 类型填git
    repo: git@github.com:MonostableLSD/monostablelsd.github.io.git # 你的Github仓库地址
    branch: master
