name: Hexo Deploy
on:
  push:
    branches:
      - hexo
env:
  GIT_USER: aemaeth
  GIT_EMAIL: monostablelss@gmail.com


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout deploy branch
        uses: actions/checkout@v2
        with:
          ref: hexo
          path: ./

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Remove Deploy_git
        run: |
          rm -rf .deploy_git

      - name: Install dependencies
        run: |
          npm install && npm run build

      - name: Hexo c & g
        run: |
          npm run build
          
      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name $GIT_USER
          git config --global user.email $GIT_EMAIL

      - name: Deploy
        run: |
          npm run deploy
